locals {
  # Common tags for all resources
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "Terraform"
    Project     = "IRIS"
  })

  # Get App Service Managed Identity principal IDs from remote state
  app_service_identities = try(
    data.terraform_remote_state.app_services.outputs.app_service_principal_ids,
    {}
  )

  # PostgreSQL Flexible Server Configuration
  postgres_servers = {
    primary = {
      name = "iris-postgres-${var.environment}"

      # Server configuration
      sku_name   = "B_Standard_B1ms" # Basic tier, 1 vCore, 2 GiB RAM - good for dev
      storage_mb = 32768              # 32 GB storage
      version    = "16"               # PostgreSQL version

      # High availability
      high_availability = {
        mode                      = "Disabled" # Disabled for dev, use "ZoneRedundant" for production
        standby_availability_zone = null
      }

      # Backup configuration
      backup_retention_days        = 7
      geo_redundant_backup_enabled = false # Set to true for production

      # Network configuration
      public_network_access_enabled = true # For dev environment
      delegated_subnet_id           = null # Set if using VNet integration

      # Authentication - Using Azure AD (Entra ID) with Managed Identity
      # A temporary admin account is still created but will be disabled after Azure AD is configured
      administrator_login    = "psqladmin"
      administrator_password = null # Will be auto-generated by Azure

      # Azure AD authentication
      authentication = {
        active_directory_auth_enabled = true
        password_auth_enabled         = false # Disable password auth, use only Azure AD
        tenant_id                     = data.azurerm_client_config.current.tenant_id
      }

      # Azure AD administrators - Grant access to app services
      # Note: PostgreSQL Flexible Server supports multiple AD admins
      azure_ad_administrators = {
        # Admin user (terraform deployer)
        terraform_admin = {
          object_id      = data.azurerm_client_config.current.object_id
          principal_name = data.azurerm_client_config.current.client_id
          principal_type = "ServicePrincipal"
        }
        # iris-claps app service
        iris_claps = {
          object_id      = try(local.app_service_identities["iris-claps"], null)
          principal_name = "iris-iris-claps-dev-001" # App service name
          principal_type = "ServicePrincipal"
        }
        # iot-ingestion app service
        iot_ingestion = {
          object_id      = try(local.app_service_identities["iot-ingestion"], null)
          principal_name = "iris-iot-ingestion-dev-001"
          principal_type = "ServicePrincipal"
        }
      }

      # Maintenance window (optional)
      maintenance_window = {
        day_of_week  = 0 # Sunday
        start_hour   = 2
        start_minute = 0
      }

      # Databases to create
      databases = {
        "iris-app" = {
          name      = "iris-app"
          charset   = "UTF8"
          collation = "en_US.utf8"
        }
        "iris-analytics" = {
          name      = "iris-analytics"
          charset   = "UTF8"
          collation = "en_US.utf8"
        }
      }

      # Firewall rules - allow Azure services
      firewall_rules = {
        "AllowAllAzureServicesAndResourcesWithinAzureIps" = {
          name             = "AllowAllAzureServicesAndResourcesWithinAzureIps"
          start_ip_address = "0.0.0.0"
          end_ip_address   = "0.0.0.0"
        }
      }
    }
  }
}
